### ISSUE TITLE
Some NONMATCHINGS are not functionally équivalent

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pmd-red#193]
Out of curiosity I built with `NONMATCHING` defined to see if the game doesn't break.

Result: Some graphical weirdness + softlock in Tiny Woods 😢 

I'm not exactly sure which one(s) are responsible for this tho
![pmd_red_02](https://github.com/user-attachments/assets/21def0f9-9134-4e5e-a1e7-b89cf12e2a72)
![pmd_red_01](https://github.com/user-attachments/assets/499c5663-9424-4423-96c4-62d28e781778)

**Comment by AnonymousRandomPerson** [comment]
Resolving with https://github.com/pret/pmd-red/pull/194

**Comment by Kermalis** [comment]
Is this still the case?

**Comment by AnonymousRandomPerson** [comment]
The linked PR from my comment fixed both the menu drawing and the sprites.
