### ISSUE TITLE
INSTALL.md is outdated and also flat-out wrong RE installing the compiler

### ISSUE THREAD

**Issue by PikalaxALT** [pret/pmd-red#3]
1) The following instruction is incorrect:

```bash
${DEVKITARM}/bin/arm-none-eabi/ranlib PATH_OF_PMD-RED_DIRECTORY/tools/agbcc/lib/libgcc.a lib/libc.a
```
Should be
```bash
${DEVKITARM}/bin/arm-none-eabi/ranlib PATH_OF_PMD-RED_DIRECTORY/tools/agbcc/lib/{libgcc.a,libc.a}
```

2) We will eventually migrate to the [new agbcc layout][luckypls] branch, which deprecates these instructions.  New instructions will be
```bash
git clone https://github.com/luckytyphlosion/agbcc -b new_layout_with_libs
cd agbcc
make
make install prefix=PATH_OF_PMD-RED_DIRECTORY
```

[luckypls]: https://github.com/luckytyphlosion/agbcc/tree/new_layout_with_libs

**Comment by Kermalis** [comment]
For me it's `${DEVKITARM}/arm-none-eabi/bin/ranlib`

**Comment by lewisje** [comment]
Also, what happened to the pret/pokeruby-tools repository mentioned in the installation instructions?

**Comment by atasro2** [comment]
> INSTALL.md is outdated

read

**Comment by EchedeyLR** [comment]
Same and worse, "No hay ninguna regla para construir el objetivo 'pmd_red.elf', necesario para 'pmd_red.gba'.  Alto."

In summary, pmd_red.gba cannot be generated because there is no rule to compile pmd_red.elf

**Comment by mid-kid** [comment]
This project is unfinished and hasn't been touched in a year. It's unlikely that you could use it for anything even if you could get it to build, unless you're interested in completing it, and I doubt it'll be fixed anytime soon.

**Comment by SethBarberee** [comment]
As long as you have the baserom, it builds fine. 

@EchedeyLR that error occurs if you don't have the baserom for building

**Comment by EchedeyLR** [comment]
Thank you for the info. I didn't check last commit date and changes and I recognize it. 

No, I don't have the baserom, I was trying to build it like Pokemon Emerald rom without the baserom.

**Comment by LOuroboros** [comment]
> No, I don't have the baserom, I was trying to build it like Pokemon Emerald rom without the baserom.

I think it's a good idea to mention that whenever you want to use projects like these and there's [a document explaining how to build it](https://github.com/pret/pmd-red/blob/master/INSTALL.md), you should go and read it before trying to do anything at all.

**Comment by EchedeyLR** [comment]
> > No, I don't have the baserom, I was trying to build it like Pokemon Emerald rom without the baserom.
> 
> I think it's a good idea to mention that whenever you want to use projects like these and there's [a document explaining how to build it](https://github.com/pret/pmd-red/blob/master/INSTALL.md), you should go and read it before trying to do anything at all.

I read it but didn't take in account the header before "Linux" because in other repos from this org was direct. I think a title marking that section as important should be added or other people could skip it too while reading.

**Comment by EchedeyLR** [comment]
To be exact, I thought that was just a description and not part of the steps itself so I just ignored it.

**Comment by EchedeyLR** [comment]
https://github.com/pret/pokeemerald/blob/master/INSTALL.md has a "Prerequisites" section at least and https://github.com/pret/pokeyellow/blob/master/INSTALL.md doesn't have anything which is just direct.
